version: '3.8'

services:
  web:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=JobTrackingDB;Username=yigit;Password=123

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: yigit
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: JobTrackingDB
    ports:
      - "6667:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
